# The simplest working Podfile!
require_relative "../../poclink-js/node_modules/react-native/scripts/react_native_pods"

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'poclink-app' do
  react_native_path = "../../poclink-js/node_modules/react-native"

  use_react_native!(
    :path => react_native_path,
    :app_path => File.expand_path("../../poclink-js"),
    :hermes_enabled => true,
    :fabric_enabled => false,
    :new_arch_enabled => false
  )

  # Our existing dependencies
  pod 'AFNetworking'
  pod 'MJExtension', '~> 3.0.13'
  pod 'YYKit'
  pod 'MMKV'
  pod 'GoogleSignIn'
  pod 'CocoaAsyncSocket'

  post_install do |installer|
    begin
      react_native_post_install(
        installer,
        react_native_path,
        :mac_catalyst_enabled => false
      )
    rescue => e
      puts "Caught error in post_install: #{e.message}"
      puts "Continuing despite error to ensure all files are generated"
    end
  end
end
